config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get 'seeds/run' => 'static#run'
  get 'static/export_clients_and_pets' => 'static#export_clients_and_pets'
  get 'static/export_appointments' => 'static#export_appointments'
  get 'static/export_classes' => 'static#export_classes'
  get 'static/export_bundles' => 'static#export_bundles'
  get 'static/export_giftcards' => 'static#export_giftcards'
  get 'static/export_inventory' => 'static#export_inventory'
  get 'static/export_salonset' => 'static#export_salonset'
  get 'static/export_salonsetwclasses' => 'static#export_salonsetwclasses'
  get 'static/export_salonsetwclasseswbundles' => 'static#export_salonsetwclasseswbundles'
  get 'static/export_salonsetwbundles' => 'static#export_salonsetwbundles'
  get 'static/yogawbundles' => 'static#yogawbundles'
  get 'static/detailingwbundles' => 'static#detailingwbundles'
  get 'static/yogawclasses' => 'static#yogawclasses'
  get 'static/detailingwclasses' => 'static#detailingwclasses'
  get 'static/yogawclasseswbundles' => 'static#yogawclasseswbundles'
  get 'static/detailingwclasseswbundles' => 'static#detailingwclasseswbundles'
  get 'static/export_petset' => 'static#export_petset'
  get 'static/export_petsetwclasses' => 'static#export_petsetwclasses'
  get 'static/export_petsetwclasseswbundles' => 'static#export_petsetwclasseswbundles'
  get 'static/export_petsetwbundles' => 'static#export_petsetwbundles'
  get 'static/export_tickets' => 'static#export_tickets'
  get 'static/export_memberships' => 'static#export_memberships'
  get 'static/yoga' => 'static#yoga'
  get 'static/detailing' => 'static#detailing'

  resources :export, only: [] do
    collection do
      get :appointments
      get :appointmentservices
      get :appointmentstatuses
      get :tickets
      get :ticketskus
      get :ticketservices
      get :tips
      get :ticketpayments
      get :giftcards
      get :batchmanifest
      get :locations
      get :pets
      get :clients
      get :customfields
      get :inventoryproducts
      get :inventoryskus
      get :inventorystocks
      get :memberships
      get :membershiplocations
      get :membershipbenefits
      get :membershipservices
      get :membershipproducts
      get :products
      get :petcategories
      get :petservices
      get :saloncategories
      get :salonservices
      get :pricings
      get :staff
      get :attendees
      get :classcategories
      get :events
      get :bundles
      get :bundle_item_groups
      get :bundle_item_group_prices
      get :bundle_items
      get :classsettings
      get :classsettingattendees
      get :classsettinglocations
      get :classsegmenttemplates
    end
  end
  resources :memberships
  resources :tickets
  resources :inventorystocks
  resources :inventoryskus
  resources :inventoryproducts
  resources :petcategories
  resources :petservices
  resources :appointments, only: %i[index export]
  resources :giftcards, only: %i[index export]
  resources :pets, only: %i[index export]
  resources :customfields, only: %i[index export]
  resources :batchmanifests, only: %i[index export]
  resources :salonpricings, only: %i[index export]
  resources :saloncategories, only: %i[index export]
  resources :staffs, only: %i[index export]
  resources :salonservices, only: %i[index export]
  resources :services, only: %i[index export]
  resources :locations, only: %i[index export]
  resources :classsegmenttemplates
  resources :classsettings
  resources :classsettinglocations
  resources :classsettingattendees
  resources :events
  resources :classcategories
  resources :attendees
  resources :clients
  resources :bundles
  resources :bundle_items
  resources :bundle_item_groups
  resources :bundle_item_group_prices
  devise_for :users

  get '*path', to: 'application#handle_404'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/attendee.rb
class Attendee < ApplicationRecord
end

app/models/batchmanifest.rb
class Batchmanifest < ApplicationRecord
end

app/models/bundle.rb
class Bundle < ApplicationRecord
end

app/models/bundle_item.rb
class BundleItem < ApplicationRecord
end

app/models/classcategory.rb
class Classcategory < ApplicationRecord
end

app/models/classsetting.rb
class Classsetting < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customfield.rb
class Customfield < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/inventorysku.rb
class Inventorysku < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/models/petcategory.rb
class Petcategory < ApplicationRecord
end

app/models/petevent.rb
class Petevent < ApplicationRecord
end

app/models/petservice.rb
class Petservice < ApplicationRecord
end

app/models/saloncategory.rb
class Saloncategory < ApplicationRecord
end

app/models/salonpricing.rb
class Salonpricing < ApplicationRecord
end

app/models/salonservice.rb
class Salonservice < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  # require 'csv'
  # require 'activerecord-import/base'
  # require 'activerecord-import/active_record/adapters/postgresql_adapter'
  #
  # def self.to_csv
  #   attributes = %w{employee_id name title email username location_id deleted}
  #   CSV.open("#{Rails.root}/app/assets/csvs/employees.csv", "wb", headers: true) do |csv|
  #     csv << attributes
  #
  #     all.each do |staff|
  #       csv << attributes.map{ |attr| staff.send(attr) }
  #     end
  #   end
  #
  #   CSV.generate(headers: true) do |csv|
  #     csv << attributes
  #
  #     all.each do |staff|
  #       csv << attributes.map{ |attr| staff.send(attr) }
  #     end
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.all
  end
end

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Membership</th>
      <th>Membership name</th>
      <th>Description</th>
      <th>Registration fee amount</th>
      <th>Cancellation fee amount</th>
      <th>Price</th>
      <th>Period size</th>
      <th>Period type</th>
      <th>Billing cycle type</th>
      <th>Billing day</th>
      <th>Payment type</th>
      <th>Location</th>
      <th>Benefit</th>
      <th>Benefit type</th>
      <th>Benefit discount type</th>
      <th>Benefit value</th>
      <th>Benefit limit</th>
      <th>Eligible for all services</th>
      <th>Eligible for all products</th>
      <th>Benefit name</th>
      <th>Service</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.membership_id %></td>
        <td><%= membership.membership_name %></td>
        <td><%= membership.description %></td>
        <td><%= membership.registration_fee_amount %></td>
        <td><%= membership.cancellation_fee_amount %></td>
        <td><%= membership.price %></td>
        <td><%= membership.period_size %></td>
        <td><%= membership.period_type %></td>
        <td><%= membership.billing_cycle_type %></td>
        <td><%= membership.billing_day %></td>
        <td><%= membership.payment_type %></td>
        <td><%= membership.location_id %></td>
        <td><%= membership.benefit_id %></td>
        <td><%= membership.benefit_type %></td>
        <td><%= membership.benefit_discount_type %></td>
        <td><%= membership.benefit_value %></td>
        <td><%= membership.benefit_limit %></td>
        <td><%= membership.eligible_for_all_services %></td>
        <td><%= membership.eligible_for_all_products %></td>
        <td><%= membership.benefit_name %></td>
        <td><%= membership.service_id %></td>
        <td><%= membership.product_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>