config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get 'seeds/run' => 'static#run'
  get 'static/export_clients_and_pets' => 'static#export_clients_and_pets'
  get 'static/export_appointments' => 'static#export_appointments'
  get 'static/export_classes' => 'static#export_classes'
  get 'static/export_bundles' => 'static#export_bundles'
  get 'static/export_giftcards' => 'static#export_giftcards'
  get 'static/export_inventory' => 'static#export_inventory'
  get 'static/export_salonset' => 'static#export_salonset'
  get 'static/export_salonsetwclasses' => 'static#export_salonsetwclasses'
  get 'static/export_salonsetwclasseswbundles' => 'static#export_salonsetwclasseswbundles'
  get 'static/export_salonsetwbundles' => 'static#export_salonsetwbundles'
  get 'static/yogawbundles' => 'static#yogawbundles'
  get 'static/detailingwbundles' => 'static#detailingwbundles'
  get 'static/yogawclasses' => 'static#yogawclasses'
  get 'static/detailingwclasses' => 'static#detailingwclasses'
  get 'static/yogawclasseswbundles' => 'static#yogawclasseswbundles'
  get 'static/detailingwclasseswbundles' => 'static#detailingwclasseswbundles'
  get 'static/export_petset' => 'static#export_petset'
  get 'static/export_petsetwclasses' => 'static#export_petsetwclasses'
  get 'static/export_petsetwclasseswbundles' => 'static#export_petsetwclasseswbundles'
  get 'static/export_petsetwbundles' => 'static#export_petsetwbundles'
  get 'static/export_tickets' => 'static#export_tickets'
  get 'static/export_memberships' => 'static#export_memberships'
  get 'static/yoga' => 'static#yoga'
  get 'static/detailing' => 'static#detailing'

  resources :export, only: [] do
    collection do
      get :appointments
      get :appointmentservices
      get :appointmentstatuses
      get :tickets
      get :ticketskus
      get :ticketservices
      get :tips
      get :ticketpayments
      get :giftcards
      get :batchmanifest
      get :locations
      get :pets
      get :clients
      get :customfields
      get :inventoryproducts
      get :inventoryskus
      get :inventorystocks
      get :memberships
      get :membershiplocations
      get :membershipbenefits
      get :membershipservices
      get :membershipproducts
      get :products
      get :petcategories
      get :petservices
      get :saloncategories
      get :salonservices
      get :pricings
      get :staff
      get :attendees
      get :classcategories
      get :events
      get :bundles
      get :bundle_item_groups
      get :bundle_item_group_prices
      get :bundle_items
      get :classsettings
      get :classsettingattendees
      get :classsettinglocations
      get :classsegmenttemplates
    end
  end
  resources :memberships
  resources :tickets
  resources :inventorystocks
  resources :inventoryskus
  resources :inventoryproducts
  resources :petcategories
  resources :petservices
  resources :appointments, only: %i[index export]
  resources :giftcards, only: %i[index export]
  resources :pets, only: %i[index export]
  resources :customfields, only: %i[index export]
  resources :batchmanifests, only: %i[index export]
  resources :salonpricings, only: %i[index export]
  resources :saloncategories, only: %i[index export]
  resources :staffs, only: %i[index export]
  resources :salonservices, only: %i[index export]
  resources :services, only: %i[index export]
  resources :locations, only: %i[index export]
  resources :classsegmenttemplates
  resources :classsettings
  resources :classsettinglocations
  resources :classsettingattendees
  resources :events
  resources :classcategories
  resources :attendees
  resources :clients
  resources :bundles
  resources :bundle_items
  resources :bundle_item_groups
  resources :bundle_item_group_prices
  devise_for :users

  get '*path', to: 'application#handle_404'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/attendee.rb
class Attendee < ApplicationRecord
end

app/models/batchmanifest.rb
class Batchmanifest < ApplicationRecord
end

app/models/bundle.rb
class Bundle < ApplicationRecord
end

app/models/bundle_item.rb
class BundleItem < ApplicationRecord
end

app/models/classcategory.rb
class Classcategory < ApplicationRecord
end

app/models/classsetting.rb
class Classsetting < ApplicationRecord
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/customfield.rb
class Customfield < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/inventorysku.rb
class Inventorysku < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/models/petcategory.rb
class Petcategory < ApplicationRecord
end

app/models/petevent.rb
class Petevent < ApplicationRecord
end

app/models/petservice.rb
class Petservice < ApplicationRecord
end

app/models/salonpricing.rb
class Salonpricing < ApplicationRecord
end

app/models/salonservice.rb
class Salonservice < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  # require 'csv'
  # require 'activerecord-import/base'
  # require 'activerecord-import/active_record/adapters/postgresql_adapter'
  #
  # def self.to_csv
  #   attributes = %w{employee_id name title email username location_id deleted}
  #   CSV.open("#{Rails.root}/app/assets/csvs/employees.csv", "wb", headers: true) do |csv|
  #     csv << attributes
  #
  #     all.each do |staff|
  #       csv << attributes.map{ |attr| staff.send(attr) }
  #     end
  #   end
  #
  #   CSV.generate(headers: true) do |csv|
  #     csv << attributes
  #
  #     all.each do |staff|
  #       csv << attributes.map{ |attr| staff.send(attr) }
  #     end
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/views/shared/_nav.html.erb
<div class="row">
		<div class="col-md-12">
      <ul class="nav nav-pills flex-column">
				<li class="nav-item">
					<a class="nav-link <%= active?(root_path) %>" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(batchmanifests_path) %>" href="/batchmanifests">Batch Manifest</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(locations_path) %>" href="/locations">Locations</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(staffs_path) %>" href="/staffs">Staff</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(saloncategories_path) %>" href="/saloncategories">Salon Services</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(petcategories_path) %>" href="/petcategories">Grooming Services</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(salonpricings_path) %>" href="/salonpricings">Service Pricing</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(clients_path) %>" href="/clients">Client Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(appointments_path) %>" href="/appointments">Appointments & Tickets</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(inventoryproducts_path) %>" href="/inventoryproducts">Inventory</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(events_path) %>" href="/events">Classes & Events</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(bundles_path) %>" href="/bundles">Bundles</a>
				</li>
				<!-- User authentication is setup. Toggle this on and set before action, if outsiders start downloading. -->
        <!-- <li class="nav-item dropdown ml-md-auto">
          <a class="nav-item" id="navbarDropdownMenuLink">
            <% if user_signed_in? %>
              <a class="dropdown-item"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></a>
            <% else %>
              <a class="dropdown-item"><%= link_to('Login', new_user_session_path) %></a>
            <% end %>
          </a>
        </li> -->
  		</ul>
  	</div>
  </div>